#!/bin/bash

function handler() {
    echo "Processing the Ctrl+C, trying to kill ssh agent"
    ssh-agent -k

    exit 1
}

function HELP() {
    echo -e "Manipulate Docker image & container."
    echo -e ""
    echo -e "\033[93mUSAGE:\033[0m"
    echo -e "    docker-cli [OPTIONS] [DOCKER COMMANDS] [DOCKER OPTIONS]"
    echo -e ""
    echo -e "\033[93mOPTIONS:\033[0m"
    echo -e "    \033[92m--id <ID>\033[0m"
    echo -e "    \tSpecific id by <ID>. Default: \`id -un\`."
    echo -e "    \033[92m--project <PROJECT>\033[0m"
    echo -e "    \tSpecific project name by <PROJECT>. Default: \"project\"."
    echo -e "    \033[92m--version <VERSION>\033[0m"
    echo -e "    \tSpecific version by <VERSION>. Default: \"latest\"."
    echo -e "    \033[92m--ssh\033[0m"
    echo -e "    \tEstablish SSH agent."
    echo -e "    \033[92m--compose\033[0m"
    echo -e "    \tUse docker compose."
    echo -e "    \033[92m-h, --help\033[0m"
    echo -e "    \tPrint this help message."
}

SSH=0
COMPOSE=0

while [[ "$1" =~ ^- && ! "$1" == "--" ]]; do
    case $1 in
    -h | --help)
        HELP

        exit 0

        ;;
    --id)
        ID=$2

        shift
        shift
        ;;
    --project)
        PROJECT=$2

        shift
        shift
        ;;
    --version)
        VERSION=$2

        shift
        shift
        ;;
    --ssh)
        SSH=1

        shift
        ;;
    --compose)
        COMPOSE=1

        shift
        ;;
    *)
        echo -e "\033[91mOption $1 not found.\033[0m"
        echo -e "Please check [-h|--help] for more details."

        exit 1

        ;;
    esac
done

if [[ "$1" == '--' ]]; then
    shift
fi

if [[ -z ${ID} ]]; then
    ID="$(id -un)"

    echo "Set default id to ${ID} ..."
fi

if [[ -z ${PROJECT} ]]; then
    PROJECT="project"

    echo "Set default project to ${PROJECT} ..."
fi

if [[ -z ${VERSION} ]]; then
    VERSION="latest"

    echo "Set default version to ${VERSION} ..."
fi

if [[ ${SSH} == 1 ]]; then
    trap handler SIGINT

    eval $(ssh-agent) && ssh-add
fi

if [[ ${COMPOSE} == 1 ]]; then
    ID=${ID} PROJECT=${PROJECT} VERSION=${VERSION} bash -c "docker compose $*"
else
    ID=${ID} PROJECT=${PROJECT} VERSION=${VERSION} bash -c "docker $*"
fi

if [[ ${SSH} == 1 ]]; then
    ssh-agent -k
fi
